/// 分类定义：key + 显示名 + emoji
class CategoryDef {
  final String key;
  final String label;
  final String emoji;
  final bool isExpense; // 支出类
  final bool isIncome; // 收入类
  final bool isTransfer; // 转账/存钱类（不算消费）

  const CategoryDef(this.key, this.label, this.emoji,
      {this.isExpense = false, this.isIncome = false, this.isTransfer = false});
}

/// 所有内置分类。转账/收入类在分析"消费"时会排除。
const List<CategoryDef> kCategories = [
  // ---- 支出 ----
  CategoryDef('food', '餐饮', '🍜', isExpense: true),
  CategoryDef('transport', '交通', '🚇', isExpense: true),
  CategoryDef('shopping', '购物', '🛍️', isExpense: true),
  CategoryDef('housing', '居住', '🏠', isExpense: true),
  CategoryDef('entertainment', '娱乐', '🎮', isExpense: true),
  CategoryDef('medical', '医疗', '💊', isExpense: true),
  CategoryDef('education', '教育', '📚', isExpense: true),
  CategoryDef('social', '人情', '🎁', isExpense: true),
  CategoryDef('comm', '通讯', '📱', isExpense: true),
  CategoryDef('daily', '日用', '🧻', isExpense: true),
  CategoryDef('other_expense', '其他支出', '📦', isExpense: true),
  // ---- 收入 ----
  CategoryDef('income_salary', '工资', '💼', isIncome: true),
  CategoryDef('income_transfer', '转入/红包', '💸', isIncome: true),
  CategoryDef('income_invest', '理财收益', '🌱', isIncome: true),
  CategoryDef('income_other', '其他收入', '💰', isIncome: true),
  // ---- 转账/存钱（不算消费）----
  CategoryDef('transfer', '账户互转', '🔄', isTransfer: true),
  CategoryDef('saving', '存钱/投资', '🏦', isTransfer: true),
  // ---- 未分类 ----
  CategoryDef('unknown', '未分类', '❓'),
];

final Map<String, CategoryDef> kCategoryMap = {
  for (final c in kCategories) c.key: c,
};

CategoryDef categoryOf(String key) =>
    kCategoryMap[key] ?? kCategoryMap['unknown']!;

/// 内置关键词规则（按顺序匹配，越靠前优先级越高）。
/// 每个元素: [关键词, 分类key]
const List<List<String>> kBuiltinRules = [
  // ===== 收入（高特指词，放最前面优先于"转账/转入"等通用词） =====
  ['工资', 'income_salary'],
  ['薪金', 'income_salary'],
  ['代发工资', 'income_salary'],
  ['奖金', 'income_salary'],
  ['生活费', 'income_transfer'],
  ['亲属', 'income_transfer'],
  ['父母', 'income_transfer'],
  ['转入红包', 'income_transfer'],
  ['红包收入', 'income_transfer'],
  ['收到红包', 'income_transfer'],
  ['收款', 'income_transfer'],
  ['零钱通收益', 'income_invest'],
  ['理财通收益', 'income_invest'],
  ['余额宝收益', 'income_invest'],
  ['基金收益', 'income_invest'],
  ['佣金', 'income_other'],
  ['退款', 'income_other'],
  ['报销', 'income_other'],
  // ===== 转账 / 存钱（不计入消费） =====
  ['基金申购', 'saving'],
  ['基金买入', 'saving'],
  ['买入基金', 'saving'],
  ['定投', 'saving'],
  ['转入零钱通', 'saving'],
  ['转入理财通', 'saving'],
  ['余额宝-转入', 'saving'],
  ['理财申购', 'saving'],
  ['购买理财', 'saving'],
  ['货币基金', 'saving'],
  ['基金赎回', 'transfer'],
  ['基金卖出', 'transfer'],
  ['转出零钱通', 'transfer'],
  ['转出理财通', 'transfer'],
  ['余额宝-转出', 'transfer'],
  ['理财赎回', 'transfer'],
  ['零钱提现', 'transfer'],
  ['提现到', 'transfer'],
  ['余额提现', 'transfer'],
  ['转账', 'transfer'],
  ['还款', 'transfer'],
  ['信用卡还款', 'transfer'],
  ['他人转账', 'transfer'],
  ['转入', 'transfer'],
  ['转出', 'transfer'],
  ['余额互转', 'transfer'],
  ['收益发放', 'income_invest'],
  ['收益到账', 'income_invest'],
  ['利息', 'income_invest'],
  ['分红', 'income_invest'],
  // 泛化兜底：平台存取类描述（不细究方向都算"中性"，不计入消费）。
  // 放在收益词之后，避免"XX收益-零钱通"这类被误判为转账
  ['提现', 'transfer'],
  ['取现', 'transfer'],
  ['零钱通', 'transfer'],
  ['理财通', 'transfer'],
  ['余额宝', 'transfer'],
  // ===== 餐饮 =====
  ['美团', 'food'],
  ['饿了么', 'food'],
  ['外卖', 'food'],
  ['餐厅', 'food'],
  ['饭店', 'food'],
  ['食堂', 'food'],
  ['麦当劳', 'food'],
  ['肯德基', 'food'],
  ['汉堡', 'food'],
  ['奶茶', 'food'],
  ['咖啡', 'food'],
  ['瑞幸', 'food'],
  ['星巴克', 'food'],
  ['小吃', 'food'],
  ['早餐', 'food'],
  ['午餐', 'food'],
  ['晚餐', 'food'],
  ['夜宵', 'food'],
  ['烧烤', 'food'],
  ['火锅', 'food'],
  ['蛋糕', 'food'],
  ['面包', 'food'],
  ['水果', 'food'],
  ['超市', 'food'],
  ['便利店', 'food'],
  ['罗森', 'food'],
  ['全家', 'food'],
  ['七十一', 'food'],
  ['711', 'food'],
  ['买菜', 'food'],
  ['菜市场', 'food'],
  ['生鲜', 'food'],
  ['叮咚', 'food'],
  ['朴朴', 'food'],
  ['食', 'food'],
  // ===== 交通 =====
  ['滴滴', 'transport'],
  ['打车', 'transport'],
  ['出租车', 'transport'],
  ['地铁', 'transport'],
  ['公交', 'transport'],
  ['铁路', 'transport'],
  ['高铁', 'transport'],
  ['火车', 'transport'],
  ['机票', 'transport'],
  ['航空', 'transport'],
  ['加油', 'transport'],
  ['中石化', 'transport'],
  ['中石油', 'transport'],
  ['停车', 'transport'],
  ['共享单车', 'transport'],
  ['哈啰', 'transport'],
  ['青桔', 'transport'],
  ['单车', 'transport'],
  ['12306', 'transport'],
  ['出行', 'transport'],
  // ===== 居住 =====
  ['房租', 'housing'],
  ['租金', 'housing'],
  ['物业', 'housing'],
  ['水电', 'housing'],
  ['电费', 'housing'],
  ['水费', 'housing'],
  ['燃气', 'housing'],
  ['气费', 'housing'],
  ['宽带', 'housing'],
  ['维修', 'housing'],
  ['家居', 'housing'],
  // ===== 购物 =====
  ['淘宝', 'shopping'],
  ['天猫', 'shopping'],
  ['京东', 'shopping'],
  ['拼多多', 'shopping'],
  ['唯品会', 'shopping'],
  ['抖音电商', 'shopping'],
  ['得物', 'shopping'],
  ['商城', 'shopping'],
  ['旗舰店', 'shopping'],
  ['服装', 'shopping'],
  ['衣服', 'shopping'],
  ['鞋', 'shopping'],
  ['数码', 'shopping'],
  ['电器', 'shopping'],
  ['手机', 'shopping'],
  ['耳机', 'shopping'],
  ['购物', 'shopping'],
  ['百货', 'shopping'],
  ['优衣库', 'shopping'],
  ['无印良品', 'shopping'],
  ['miniso', 'shopping'],
  ['名创优品', 'shopping'],
  // ===== 娱乐 =====
  ['游戏', 'entertainment'],
  ['steam', 'entertainment'],
  ['王者', 'entertainment'],
  ['原神', 'entertainment'],
  ['腾讯视频', 'entertainment'],
  ['爱奇艺', 'entertainment'],
  ['优酷', 'entertainment'],
  ['bilibili', 'entertainment'],
  ['哔哩哔哩', 'entertainment'],
  ['会员', 'entertainment'],
  ['电影', 'entertainment'],
  ['影院', 'entertainment'],
  ['ktv', 'entertainment'],
  ['酒吧', 'entertainment'],
  ['剧本杀', 'entertainment'],
  ['娱乐', 'entertainment'],
  ['景点', 'entertainment'],
  ['门票', 'entertainment'],
  ['旅游', 'entertainment'],
  ['酒店', 'entertainment'],
  ['民宿', 'entertainment'],
  ['健身房', 'entertainment'],
  ['运动', 'entertainment'],
  ['球', 'entertainment'],
  // ===== 医疗 =====
  ['医院', 'medical'],
  ['药店', 'medical'],
  ['药房', 'medical'],
  ['诊所', 'medical'],
  ['挂号', 'medical'],
  ['看病', 'medical'],
  ['体检', 'medical'],
  ['牙', 'medical'],
  ['医疗', 'medical'],
  // ===== 教育 =====
  ['学费', 'education'],
  ['课程', 'education'],
  ['培训', 'education'],
  ['网课', 'education'],
  ['书籍', 'education'],
  ['书店', 'education'],
  ['当当', 'education'],
  ['kindle', 'education'],
  ['教育', 'education'],
  ['知识付费', 'education'],
  // ===== 人情 =====
  ['红包', 'social'],
  ['礼金', 'social'],
  ['份子', 'social'],
  ['礼物', 'social'],
  ['礼品', 'social'],
  ['请客', 'social'],
  // ===== 通讯 =====
  ['话费', 'comm'],
  ['充值中心', 'comm'],
  ['流量', 'comm'],
  ['中国移动', 'comm'],
  ['中国联通', 'comm'],
  ['中国电信', 'comm'],
  ['通讯', 'comm'],
];
